---
- name: Install Fail2Ban
  apt:
          name: "fail2ban"
          state: latest

- name: Template custom rules
  template:
          src: templates/jail.local.j2
          dest: /etc/fail2ban/jail.local
          mode: 0644
